### ISSUE TITLE
Counts Draws as Losses

### ISSUE THREAD

**Issue by memerson12** [cltWilly/mcsrr-widget#2]
https://github.com/cltWilly/mcsrr-widget/blob/c04df9dd7d5828d204509290edfb0f98be2e0047/app/generator/page.jsx#L27-L42

I just briefly looked over the code, so sorry if I didn't see it handled elsewhere, but based on this function above, the widget will count draws as losses.

This is how I did it in [my implementation](https://github.com/memerson12/MCSR-Ranked-Matches-Today/blob/629ce359fb6e850ac50da19afcc54af7ae5cbab3/api/matches.js#L80-L86):
```js
totalMatchesCount++;
const resultUUID = match.result?.uuid;

if (resultUUID === userUUID) {
    wonMatchesCount++;
} else if (resultUUID === null) {
    drawCount++;
}
```

**Comment by cltWilly** [comment]
You're absolutely right. It's true that I somehow forgot about "draw" :D. Thanks for noticing. I'll definitely implement it. Now I have something in the dev branch and when I test it, I'll definitely deploy it.

**Comment by memerson12** [comment]
I also somehow completely forgot about draws when making my thing lol. Didn't realize until someone else pointed it out
